<? session_start() ?>
<!DOCTYPE html>
<html lang="es-mx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-Edge">
        <meta name="author" content="Eric A. Rodríguez S. <eazicomservicios@gmail.com>">
        <meta name="description" content="Sistema de información para los Centros de E.L.I. en Quintana Roo.">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <base href="https://eazicom.php.com:81/eliqroo">

        <? if( isset( $_SESSION[ 'centro' ] ) ): ?>
            <title><?= $_SESSION[ 'centro' ] ?></title>
        <? else: ?>
            <title>Evangelización Liberadora Integral</title>
        <? endif ?>

    </head>
    <body></body>
</html>
