<!DOCTYPE html>
<html lang="es-mx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-Edge">
        <meta name="author" content="Eric A. Rodríguez S. <eazicomservicios@gmail.com>">
        <meta name="description" content="Sistema de información para los Centros de E.L.I. en Quintana Roo.">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <base href="http://eazicom.php.com:81/eliqroo/">
        <title>Evangelización Liberadora Integral</title>

        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen" preload>
        <link href="css/app.min.css" rel="stylesheet" type="text/css" media="screen" preload>
    </head>
    <body>
        <main class="container">
            <h1>Estoy funcionando...</h1>
        </main>
        <script type="text/javascript" src="js/bootstrap.bundle.min.js" defer></script>
    </body>
</html>
