<? session_start(); ?>
<!DOCTYPE html>
<html lang="es-mx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-Edge">
        <meta name="author" content="Eric A. Rodríguez S. <eazicomservicios@gmail.com>">
        <meta name="description" content="Sistema de información para los Centros de E.L.I. en Quintana Roo.">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <base href="<?= BASE ?>">

        <? if( isset( $_SESSION[ "sesion" ][ "centro" ] ) ): ?>
            <title>Centro: <?= $_SESSION[ "sesion" ][ "centro" ] ?></title>
        <? else: ?>
            <title>Evangelización Liberadora Integral</title>
        <? endif ?>

        <link href="favicon.png" rel="shortcut icon" type="image/png" sizes="*">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen" preload>
        <link href="css/app.min.css" rel="stylesheet" type="text/css" media="screen" preload>
    </head>
    <body>
        <? include_once( "components/navbar.component.phtml" ); ?>
        <main class="container mt-5">
            <h1>Estoy en línea...</h1>
        </main>
        <script type="application/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" defer></script>
    </body>
</html>
