<nav class="navbar navbar-expand-lg bg-body-secondary shadow">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="Content/Images/eli-logo.png" alt="Evangelización Liberadora Integral">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="#">M. de Comunidades</a>
                <li class="nav-item">
                    <a class="nav-link" href="#">Comunidades</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
    </div>
</nav>